### PR TITLE
164528982 View articles on landing page

### PR DESCRIPTION
**Pull request by pbkabali**
#### Description
Load the latest 10 articles from database on landing page 

#### Type of change
- Feature

#### Checklist
- add article list and article component
- setup state handling and fetch logic for articles
- add styling for view article component

#### Relevant PT Stories

[164528982](https://www.pivotaltracker.com/story/show/164528982)

### CODE REVIEW

**Review by missvicki — CHANGES_REQUESTED** [review]
Nice work. Could you please reduce on that font though. It is too big.

**Review by oma0256 — APPROVED** [review]
Great work @pbkabali and @Karuhanga for keeping the design consistent with that of the prototypes. Work looks good

**Review by codjoero — COMMENTED** [review]
Great work guys, articles look great. On the mobile view, I feel like we are underutilizing the screen, the article cards are squeezed a lot yet ample space is left out. also for such a small display, we could reduce the size of the article card, maybe even render the image inline with the text..

**Review by missvicki — COMMENTED** [review]
Just adding on my previous comment, I think it would have been better if only the title was made clickable and not the whole article card

**Comment by karuhanga** [comment]
> Great work guys, articles look great. On the mobile view, I feel like we are underutilizing the screen, the article cards are squeezed a lot yet ample space is left out. also for such a small display, we could reduce the size of the article card, maybe even render the image inline with the text..

@codjoero nice catch there. Fixed that.

**Comment by karuhanga** [comment]
> Nice work. Could you please reduce on that font though. It is too big.

I don't think the font is too big though. I have reduced that for the article metadata though, it did look big.

**Review by codjoero — APPROVED** [review]
Thanks for the changes, look into those font sizes too.

**Review by collinewait — APPROVED** [review]

**Pull request merged**
