### PR TITLE
163383132 Implement user Registration

### PR DESCRIPTION
**Pull request by fahdjamy**
#### Description
---
Enable users to signup to Authors Haven
#### Type of change
---
Feature
#### Type of change
---
- add a signup form
- add validations for user inputs
- implement redux store and state
- add tests for the functionality
#### Relevant Story ID
[163383132](https://www.pivotaltracker.com/story/show/163383132)

### CODE REVIEW

**Review by missvicki — APPROVED** [review]
with all these hound issues, it is difficult to come up with a conclusion. I like what you've done basing on what I have seen locally.

**Review by missvicki — COMMENTED** [review]
Adding onto my previous comment. Could you please reduce the space between your header. Please change the color of the buttons as well. Also Login is not supposed to be a button as per the mockups, it is a link that leads back to login page.. Make the buttons rounded by adding border radius onto them. Keep the colors as per the mockups. Please refer to the mockups designed.

**Review by oma0256 — APPROVED** [review]
@FahdJamy clean interface and good work on the designs on the error messages.

**Comment by fahdjamy** [comment]
I have worked on the changes you requested for.
Thanks for the feedback @missvicki.

**Comment by FahdJamy** [comment]
> Adding onto my previous comment. Could you please reduce the space between your header. Please change the color of the buttons as well. Also Login is not supposed to be a button as per the mockups, it is a link that leads back to login page.. Make the buttons rounded by adding border radius onto them. Keep the colors as per the mockups. Please refer to the mockups designed.

**Pull request closed without merging**
