### PR TITLE
163383141 Implement like dislike articles

### PR DESCRIPTION
**Pull request by fahdjamy**
#### Description
---
Authenticated users (including authors) can like or dislike a particular article

- add reducer actions to like or revert like of an article to
authenticated users only
- add reducer actions to dislike or revert dislike of an article to
authenticated users only
- write tests

#### Type of change
---
- New Feature
#### How Has This Been Tested?
---
- Unit tests
#### Screenshots
---
- When a user likes an article.
image
- When a user dislikes an article
image
- When a user neither likes nor dislikes an article
image
#### Relevant Pivotal Tracker stories
---
[163383141](https://www.pivotaltracker.com/story/show/163383141)

### CODE REVIEW

**Review by karuhanga — APPROVED** [review]
LGTM

**Review by oma0256 — APPROVED** [review]
@FahdJamy nice work looks good

**Review by missvicki — APPROVED** [review]

**Review by codjoero — APPROVED** [review]
LGTM

**Comment by pbkabali** [comment]
@FahdJamy this is good work. From a users standpoint thou, I would have preferred a message asking me to log in instead of an automatic redirect when not authenticated. Other than that, this LGTM

**Review by pbkabali — APPROVED** [review]

**Pull request merged**
