### PR TITLE
164368300-chore: Setup Heroku

### PR DESCRIPTION
**Pull request by fahdjamy**
#### Description
---
Ah-frontend-summer is currently deployed on Heroku and it goes through 3 phases. The staging phase for the PR, the review app phase for the PRs, the staging phase, and the production phase. 
#### Type of change
---
No code change performed but rather this PR has setup files that help deployment on Heroku to be successful.
#### JIRA
----
[PT-164368300](https://www.pivotaltracker.com/story/show/164368300)

### CODE REVIEW

**Review by missvicki — APPROVED** [review]

**Review by karuhanga — APPROVED** [review]
LGTM

**Review by codjoero — APPROVED** [review]
LGTM

**Comment by pbkabali** [comment]
This is nice work @FahdJamy. I think it would be good to provide the heroku link to our app in the PR message. Otherwise well done

**Review by pbkabali — APPROVED** [review]

**Comment by collinewait** [comment]
Improve on the commit message.

**Review by oma0256 — APPROVED** [review]

**Comment by collinewait** [comment]
Improve on the commit message.

**Comment by fahdjamy** [comment]
> Improve on the commit message.

Worked on @collinewait

**Pull request merged**
