### PR TITLE
#163383128: Integrate travis with the project

### PR DESCRIPTION
**Pull request by oma0256**
**Description**
 - Run tests for each commit made to the repo

**Tasks completed**
 - Add .travis.yml file for travis configurations
 - Add coverage script to package.json to run tests and display coverage in travis
 - Add App.test.js to demonstrate travis in action

**What are the relevant Pivotal Tracker stories?**
[#163383128](https://www.pivotaltracker.com/n/projects/2240000/stories/163383128)

### CODE REVIEW

**Comment by pbkabali** [comment]
Good work @oma0256. LGTM

**Review by fahdjamy — APPROVED** [review]
LGTM

**Review by pbkabali — APPROVED** [review]

**Review by karuhanga — APPROVED** [review]
LGTM

**Review by codjoero — APPROVED** [review]
LGTM

**Review by collinewait — APPROVED** [review]

**Pull request merged**
