### PR TITLE
164398732 Setup pull-request-template

### PR DESCRIPTION
**Pull request by codjoero**
#### Description
#
The pull request template will help us create great pull request descriptions that follow the engineering playbook, thus meeting the organization's standards.

#### Type of change
#
- Added a docs folder with the PR-template markdown file.

#### What are the relevant Pivotal Tracker stories?
#
[#164398732](https://www.pivotaltracker.com/story/show/164398732)

### CODE REVIEW

**Review by missvicki — APPROVED** [review]
Amazing work @codjoero

**Comment by pbkabali** [comment]
Very good work here @codjoero. And you are impressively quick on your feet!

**Review by pbkabali — APPROVED** [review]

**Review by karuhanga — APPROVED** [review]
LGTM

**Review by oma0256 — APPROVED** [review]
Good work @codjoero

**Review by collinewait — APPROVED** [review]

**Pull request merged**
